const student=[
    {
        "id":"101",
        "name":"Anil",
        "college":"Jntuh",
        "marks":"72",
        "fees":80000
    },
    {
        "id":"102",
        "name":"sathish",
        "college":"SBIT",
        "marks":"80",
        "fees":"60000"
    },
    {
        "id":"103",
        "name":"Naveen",
        "college":"MGIT",
        "marks":60,
        "fees":50000
    },
    {
        "id":"104",
        "name":"Viplav",
        "college":"MLRD",
        "marks":89,
        "fees":40000
    },
    {
        "id":"105",
        "name":"Ram",
        "college":"CBIT",
        "marks":65,
        "fees":75000
    },
    {
        "id":"106",
        "name":"Raj",
        "college":"SBIT",
        "marks":69,
        "fees":85000
    },
    {
        "id":"107",
        "name":"Rohith",
        "college":"OU",
        "marks":80,
        "fees":96000
    },
    {
        "id":"108",
        "name":"Ajay",
        "college":"JNTUH",
        "marks":80,
        "fees":95000
    },
    {
        "id":"109",
        "name":"Raju",
        "college":"OU",
        "marks":60,
        "fees":95000
    },
    {
        "id":"110",
        "name":"Rajkumar",
        "college":"OU",
        "marks":80,
        "fees":95000
    },
]
export function getstudData(){
    return student
}